import { Injectable, signal } from '@angular/core';

export type LanguageCode = 'en' | 'fr';

interface TranslationMap {
  [key: string]: Record<string, string>;
}

const TRANSLATIONS: TranslationMap = {
  en: {
    explore: 'Explore',
    host: 'Host',
    bookings: 'My Bookings',
    wishlist: 'My Wishlist',
    admin: 'Admin',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    translate: 'Translate',
    translateHint: 'Switch language',
    welcomeBack: 'Welcome back',
    loginSubtitle: 'Login to manage your trips or host your home.',
    username: 'Username',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    rememberMe: 'Remember me',
    signingIn: 'Signing in...',
    logIn: 'Log In',
    orContinueWith: 'or continue with',
    dontHaveAccount: "Don't have an account?",
    signUp: 'Sign up',
    createAccount: 'Create an account',
    registerSubtitle: 'Join AelithraStay to find your next stay or start hosting.',
    email: 'Email',
    firstName: 'First name',
    lastName: 'Last name',
    hostToggleLabel: 'I want to host',
    hostToggleNote: 'List your space and earn extra income.',
    termsAgreement: 'By continuing, you agree to our Terms of Service and Privacy Policy.',
    creating: 'Creating...',
    alreadyHaveAccount: 'Already have an account?',
    logInLink: 'Log in',
    adminPortal: 'Admin Portal',
    adminSubtitle: 'Secure access for administrators only',
    adminEmail: 'Admin Email',
    rememberDevice: 'Remember this device',
    authenticating: 'Authenticating...',
    enterAdminPanel: 'Enter Admin Panel',
    notAnAdmin: 'Not an admin?',
    backToLogin: 'Back to Login',
    paymentMode: 'Mode of payment',
    paymentModeSelected: 'Selected method:',
    paymentOptionHint: 'Click “Mode of payment” to view optional payment details.',
    addPaymentMethod: 'Add a payment method',
    paymentPanelDescription: 'Add a payment method now or reserve without payment details.',
    close: 'Close',
    next: 'Next',
    cardNumber: 'Card number',
    expiry: 'Expiry',
    cvc: 'CVC',
    postalCode: 'Postal code',
    countryRegion: 'Country / region',
    paymentCardLabel: 'Visa / Mastercard / Amex',
    paymentNotePaypal: 'You can complete payment with PayPal after booking.',
    paymentNoteGooglePay: 'Google Pay will be available when confirming your reservation.',
    findNextStay: 'Find your next stay',
    unforgettable: 'unforgettable',
    discoverUnique: 'Discover unique homes, luxury villas, and cozy cabins around the world.',
    location: 'Location',
    whereGoing: 'Where are you going?',
    country: 'Country',
    addCountry: 'Add country',
    guests: 'Guests',
    addGuests: 'Add guests',
    search: 'Search',
    amazingPools: 'Amazing pools',
    beachfront: 'Beachfront',
    cabins: 'Cabins',
    luxe: 'Luxe',
    trending: 'Trending',
    countryside: 'Countryside',
    castles: 'Castles',
    topCities: 'Top cities',
    new: 'New',
    night: 'night',
    noPropertiesFound: 'No properties found',
    tryAdjustingFilters: 'Try adjusting your filters to find what you\'re looking for.',
    clearAllFilters: 'Clear all filters',
    stayOfWeek: 'Stay of the week',
    viewDetails: 'View Details',
    becomeHost: 'Become a Host and unlock a world of possibilities',
    shareHome: 'Share your home and connect with travelers from across the globe. AelithraStay gives you the tools to welcome guests with confidence and earn extra income.',
    getStarted: 'Get Started',
    hostingChangedLife: '"Hosting changed our lives. We\'ve met amazing people from every corner of the world."',
    usernameHint: 'Lowercase, numbers, and . @ + - allowed.',
    exploreStays: 'Explore stays',
    share: 'Share',
    save: 'Save',
    saving: 'Saving...',
    reviewsCount: 'reviews',
    entire: 'Entire',
    hostedBy: 'hosted by',
    bedroom: 'bedroom',
    bedrooms: 'bedrooms',
    bed: 'bed',
    beds: 'beds',
    bath: 'bath',
    baths: 'baths',
    guest: 'guest',
    guestsCount: 'guests',
    superhost: 'is a Superhost',
    superhostDesc: 'Superhosts are experienced, highly rated hosts who are committed to providing great stays for guests.',
    greatLocation: 'Great location',
    greatLocationDesc: '95% of recent guests gave the location a 5-star rating.',
    freeCancellation: 'Free cancellation for 48 hours',
    freeCancellationDesc: 'Get a full refund if you change your mind.',
    aboutPlace: 'About this place',
    showMore: 'Show more',
    showLess: 'Show less',
    offers: 'What this place offers',
    essentialAmenities: 'Essential amenities provided by the host.',
    hideAmenities: 'Hide amenities',
    showAllAmenities: 'Show all',
    leaveReview: 'Leave a review',
    howWasStay: 'How was your stay?',
    posting: 'Posting...',
    postReview: 'Post Review',
    noReviewsYet: 'No reviews yet for this property. Be the first to share your experience!',
    beFirstReview: 'Be the first to share your experience!',
    reserve: 'Reserve',
    reserving: 'Reserving...',
    checkIn: 'Check-in',
    checkOut: 'Check-out',
    wonChargeYet: 'You won\'t be charged yet',
    cleaningFee: 'Cleaning fee',
    serviceFee: 'Service fee',
    total: 'Total',
    reportListing: 'Report this listing',
    findingDreamStay: 'Finding your dream stay...',
    addedWishlist: 'Added to your wishlist!',
    alreadyWishlist: 'Already in your wishlist.',
    linkCopied: 'Link copied to clipboard!',
    copyLink: 'Copy Link',
    shareVia: 'Share via',
    thankYouReview: 'Thank you for your review!',
    alreadyReviewed: 'You have already reviewed this property.',
    loginToReserve: 'Please login to reserve this stay.',
    loginToReview: 'Please login to post a review.',
    checkOutAfterCheckIn: 'Check-out date must be after check-in date.',
    fillDetailsCorrectly: 'Please fill in all booking details correctly.',
    bookingSuccessful: 'Reservation successful! Redirecting...',
    couldNotBook: 'Could not create booking. Please check availability.',
    couldNotPostReview: 'Could not post review. Ensure all fields are filled and you have not reviewed this yet.',
    couldNotSave: 'Could not save. Login may be required.',
    creditOrDebitCard: 'Credit or debit card',
    trips: 'Trips',
    upcomingReservations: 'Upcoming reservations',
    allUpcomingReservations: 'All your upcoming reservations and travel memories in one place.',
    stay: 'Stay',
    noReservationsYet: 'No reservations yet',
    bookFirstStay: 'Book your first stay and it will appear here.',
    startExploring: 'Start exploring',
    whereYouveBeen: 'Where you\'ve been',
    reliveMemories: 'Relive your favorite travel memories',
    viewAll: 'View all',
    cantFindReservation: 'Can\'t find your reservation?',
    cantFindReservationDesc: 'If you don\'t see your trip here, it may have been booked with a different email address.',
    visitHelpCenter: 'Visit Help Center',
    historicalTripsSync: 'Historical trips archive is being synchronized.',
    saved: 'Saved',
    yourWishlist: 'Your wishlist',
    removeFromWishlist: 'Remove from wishlist',
    noSavedStays: 'No saved stays yet',
    clickHeartToSave: 'Click the heart icon on any property to save it here for later.',
    exploreProperties: 'Explore properties',
    adminPortalTitle: 'AelithraStay Admin',
    managementPortal: 'Management Portal',
    propertyListings: 'Property Listings',
    propertyApproval: 'Property Approval',
    disputesTitle: 'Disputes',
    reviewModeration: 'Review Moderation',
    userManagement: 'User Management',
    notificationsTitle: 'Notifications',
    analyticsTitle: 'Analytics',
    addNewListing: 'Add New Listing',
    searchRecords: 'Search records...',
    export: 'Export',
    listing: 'Listing',
    totalUsers: 'Total Users',
    activeListings: 'Active Listings',
    revenueTitle: 'Revenue',
    recentReservations: 'Recent Reservations',
    quickActions: 'Quick Actions',
    userDirectory: 'User Directory',
    bookingDisputes: 'Booking Disputes',
    propertyApprovalQueue: 'Property Approval Queue',
    adminNotificationCenter: 'Admin Notifications Center',
    revenuePerformance: 'Revenue Performance',
    globalPresence: 'Global Presence',
    account: 'Account',
    yourProfile: 'Your Profile',
    editProfile: 'Edit Profile',
    securitySettings: 'Security Settings',
    emailAddress: 'Email address',
    phoneNumber: 'Phone number',
    notProvided: 'Not provided',
    about: 'About',
    noBioYet: 'No bio yet. Tell guests and hosts a little about yourself.',
    accountType: 'Account type',
    bio: 'Bio',
    profileUpdated: 'Profile updated successfully.',
    securitySettingsNotAvailable: 'Password and security settings are not available yet.',
    pleaseLogin: 'Please login',
    loginToViewProfile: 'You need to be logged in to view and manage your profile settings.',
    loginNow: 'Login now',
    reservationConfirmed: 'Your reservation is confirmed!',
    confirmationEmailSent: 'A confirmation email is on its way to your inbox.',
    confirmationCode: 'Confirmation Code',
    reservation: 'reservation',
    hostedStay: 'Hosted stay',
    hostIsReady: 'Your host is ready',
    checkInDetails: 'Check-in details will be shared before arrival.',
    reservationDetails: 'Reservation Details',
    priceBreakdown: 'Price Breakdown',
    stayTotal: 'Stay total',
    viewTrips: 'View Trips',
    contactHost: 'Contact Host',
    printPdf: 'Print PDF',
    loadingConfirmation: 'Loading confirmation...',
    gettingThere: 'Getting there',
    arrivalInstructions: 'Check your email for map and arrival instructions.',
    cancellationPolicy: 'Cancellation policy',
    reviewTripPolicies: 'Review your trip policies before making changes.',
    needHelp: 'Need help?',
    reachSupport: 'Reach out to support from your profile anytime.',
    hostStudio: 'Host Studio',
    manageEmpire: 'Manage your empire',
    manageEmpireDesc: 'Welcome back! Here\'s where you turn your space into someone\'s next memory.',
    createNewListing: 'Create new listing',
    provideDetails: 'Provide details to attract guests from around the world.',
    basicInformation: 'Basic Information',
    listingTitle: 'Listing Title',
    listingTitlePlaceholder: 'e.g. Modern Minimalist Beachfront Villa',
    descriptionPlaceholder: 'Tell guests what makes your place unique...',
    propertyType: 'Property Type',
    pricePerNight: 'Price per night',
    addressPlaceholder: '123 Ocean Drive',
    cityPlaceholder: 'e.g. Malibu',
    countryPlaceholder: 'e.g. USA',
    layoutCapacity: 'Layout & Capacity',
    publishListing: 'Publish Listing',
    publishing: 'Publishing...',
    myProperties: 'My Properties',
    noPropertiesListed: 'You haven\'t listed any properties yet.',
    startByFillingForm: 'Start by filling out the form to the left.',
    listingPublished: 'Listing published successfully!',
    noPermissionHost: 'You do not have permission to host. Please register as a Host.',
    couldNotPublish: 'Could not publish listing. Please check all fields.',
    listingRemoved: 'Listing removed.',
    hostedProperties: 'Hosted Properties',
    helpCenter: 'Help Center',
    support: 'Support',
    findSolutions: 'Find solutions to common issues and contact our support team.',
    tryTheseSteps: 'Try these steps:',
    checkOtherEmails: 'Check other email addresses:',
    checkOtherEmailsDesc: 'You might have used a different email (e.g., work vs. personal) when booking.',
    searchInbox: 'Search your inbox:',
    searchInboxDesc: 'Look for "AelithraStay" or "Confirmation" in your email. Don\'t forget to check the Spam or Promotions folders.',
    verifyAccount: 'Verify your account:',
    verifyAccountDesc: 'Ensure you are logged into the correct account on AelithraStay.',
    waitSync: 'Wait for synchronization:',
    waitSyncDesc: 'Sometimes it takes a few minutes for a new booking to appear in your list.',
    faqTitle: 'Frequently Asked Questions',
    faqCancelTitle: 'How do I cancel a booking?',
    faqCancelDesc: 'Go to your Trips, select the reservation, and look for the "Cancel" button. Note the cancellation policy.',
    faqChargeTitle: 'When will I be charged?',
    faqChargeDesc: 'Typically, you are charged once the host confirms your reservation or at the time of booking depending on the property.',
    faqContactHostTitle: 'How do I contact my host?',
    faqContactHostDesc: 'After a booking is confirmed, you can find the "Contact Host" button in your trip details.',
    stillNeedHelp: 'Still need help?',
    supportDesc: 'Our dedicated support team is available 24/7 to assist you with any issues.',
    contactSupport: 'Contact Support',
    backToTrips: 'Back to Trips',
    aboutUser: 'About the Developer',
    devProfile: 'Developer Profile',
    devMission: 'Mission',
    devMissionText: 'Engineering digital ecosystems where architectural precision meets uncompromising security.',
    devBelief: 'AelithraStay is engineered on the absolute belief that modern web applications must be as robust and secure under the hood as they are seamless and elegant on the surface.',
    whyAelithra: 'Why AelithraStay?',
    devLabText: 'This project was born from a desire to bridge the gap between high-level application development and low-level system security. It serves as a laboratory for:',
    fullStackConv: 'Full-Stack Convergence',
    fullStackConvDesc: 'Seamlessly integrating a decoupled Django REST API with a reactive Angular 21 frontend.',
    defensiveEng: 'Defensive Engineering',
    defensiveEngDesc: 'Implementing strict role-based access control, admin audit logs, and account suspension workflows to mirror real-world security demands.',
    uxFluidity: 'UX Fluidity',
    uxFluidityDesc: 'Proving that a complex management system can remain intuitive through clean CSS and thoughtful state management.',
    globalReady: 'Global Readiness',
    globalReadyDesc: 'Building for an international audience with baked-in multi-language support (i18n).',
    frontendEngine: 'Frontend Engine',
    backendCore: 'Backend Core',
    dataMgmt: 'Data Management',
    securityAudit: 'Security Audit',
    contactDev: 'Contact Developer',
    securityMindset: 'Security First Mindset',
    backToApp: 'Back to Application'
  },
  fr: {
    explore: 'Explorer',
    host: 'Héberger',
    bookings: 'Mes réservations',
    wishlist: 'Mes favoris',
    admin: 'Admin',
    login: 'Connexion',
    register: 'Inscription',
    logout: 'Déconnexion',
    translate: 'Traduire',
    translateHint: 'Changer de langue',
    welcomeBack: 'Bon retour',
    loginSubtitle: 'Connectez-vous pour gérer vos voyages ou héberger votre logement.',
    username: "Nom d'utilisateur",
    password: 'Mot de passe',
    forgotPassword: 'Mot de passe oublié ?',
    rememberMe: 'Se souvenir de moi',
    signingIn: 'Connexion en cours...',
    logIn: 'Se connecter',
    orContinueWith: 'ou continuer avec',
    dontHaveAccount: "Vous n'avez pas de compte ?",
    signUp: "S'inscrire",
    createAccount: 'Créer un compte',
    registerSubtitle: 'Rejoignez AelithraStay pour trouver votre prochain séjour ou commencer à héberger.',
    email: 'E-mail',
    firstName: 'Prénom',
    lastName: 'Nom',
    hostToggleLabel: 'Je veux héberger',
    hostToggleNote: 'Listez votre espace et gagnez des revenus supplémentaires.',
    termsAgreement: 'En continuant, vous acceptez nos conditions d’utilisation et notre politique de confidentialité.',
    creating: 'Création...',
    alreadyHaveAccount: 'Vous avez déjà un compte ?',
    logInLink: 'Se connecter',
    adminPortal: 'Portail Admin',
    adminSubtitle: 'Accès sécurisé pour les administrateurs uniquement',
    adminEmail: 'E-mail Admin',
    rememberDevice: 'Se souvenir de cet appareil',
    authenticating: 'Authentification...',
    enterAdminPanel: 'Entrer dans le panneau Admin',
    notAnAdmin: 'Pas un administrateur ?',
    backToLogin: 'Retour à la connexion',
    paymentMode: 'Mode de paiement',
    paymentModeSelected: 'Mode sélectionné :',
    paymentOptionHint: 'Cliquez sur « Mode de paiement » pour afficher les informations optionnelles.',
    addPaymentMethod: 'Ajoutez un mode de paiement',
    paymentPanelDescription: 'Ajoutez un moyen de paiement maintenant ou réservez sans détails de paiement.',
    close: 'Fermer',
    next: 'Suivant',
    cardNumber: 'Numéro de carte',
    expiry: 'Expiration',
    cvc: 'CVC',
    postalCode: 'Code postal',
    countryRegion: 'Pays / région',
    paymentCardLabel: 'Visa / Mastercard / Amex',
    paymentNotePaypal: 'Vous pouvez finaliser le paiement avec PayPal après la réservation.',
    paymentNoteGooglePay: 'Google Pay sera disponible au moment de confirmer votre réservation.',
    findNextStay: 'Trouvez votre prochain séjour',
    unforgettable: 'inoubliable',
    discoverUnique: 'Découvrez des maisons uniques, des villas de luxe et des chalets confortables partout dans le monde.',
    location: 'Emplacement',
    whereGoing: 'Où allez-vous ?',
    country: 'Pays',
    addCountry: 'Ajouter un pays',
    guests: 'Voyageurs',
    addGuests: 'Ajouter des voyageurs',
    search: 'Rechercher',
    amazingPools: 'Piscines incroyables',
    beachfront: 'Bord de mer',
    cabins: 'Chalets',
    luxe: 'Luxe',
    trending: 'Tendances',
    countryside: 'Campagne',
    castles: 'Châteaux',
    topCities: 'Grandes villes',
    new: 'Nouveau',
    night: 'nuit',
    noPropertiesFound: 'Aucune propriété trouvée',
    tryAdjustingFilters: 'Essayez d’ajuster vos filtres pour trouver ce que vous cherchez.',
    clearAllFilters: 'Effacer tous les filtres',
    stayOfWeek: 'Séjour de la semaine',
    viewDetails: 'Voir les détails',
    becomeHost: 'Devenez hôte et ouvrez un monde de possibilités',
    shareHome: 'Partagez votre maison et connectez-vous avec des voyageurs du monde entier. AelithraStay vous donne les outils pour accueillir des invités en toute confiance et gagner un revenu supplémentaire.',
    getStarted: 'Commencer',
    hostingChangedLife: '« Héberger a changé notre vie. Nous avons rencontré des gens formidables de tous les coins du monde. »',
    usernameHint: 'Minuscules, chiffres et . @ + - autorisés.',
    exploreStays: 'Explorer les séjours',
    share: 'Partager',
    save: 'Enregistrer',
    saving: 'Enregistrement...',
    reviewsCount: 'commentaires',
    entire: 'Logement entier',
    hostedBy: 'hôte :',
    bedroom: 'chambre',
    bedrooms: 'chambres',
    bed: 'lit',
    beds: 'lits',
    bath: 'salle de bain',
    baths: 'salles de bain',
    guest: 'voyageur',
    guestsCount: 'voyageurs',
    superhost: 'est Superhôte',
    superhostDesc: 'Les Superhôtes sont des hôtes expérimentés et très bien notés qui s’engagent à offrir d’excellents séjours aux voyageurs.',
    greatLocation: 'Emplacement exceptionnel',
    greatLocationDesc: '95 % des voyageurs récents ont attribué 5 étoiles à l’emplacement.',
    freeCancellation: 'Annulation gratuite pendant 48 heures',
    freeCancellationDesc: 'Bénéficiez d’un remboursement intégral si vous changez d’avis.',
    aboutPlace: 'À propos de ce logement',
    showMore: 'En savoir plus',
    showLess: 'Afficher moins',
    offers: 'Ce que propose ce logement',
    essentialAmenities: 'Équipements essentiels fournis par l’hôte.',
    hideAmenities: 'Masquer les équipements',
    showAllAmenities: 'Afficher les',
    leaveReview: 'Laisser un commentaire',
    howWasStay: 'Comment s’est passé votre séjour ?',
    posting: 'Publication...',
    postReview: 'Publier le commentaire',
    noReviewsYet: 'Aucun commentaire pour le moment. Soyez le premier à partager votre expérience !',
    beFirstReview: 'Soyez le premier à partager votre expérience !',
    reserve: 'Réserver',
    reserving: 'Réservation...',
    checkIn: 'Arrivée',
    checkOut: 'Départ',
    wonChargeYet: 'Aucun montant ne sera débité pour le moment',
    cleaningFee: 'Frais de ménage',
    serviceFee: 'Frais de service',
    total: 'Total',
    reportListing: 'Signaler cette annonce',
    findingDreamStay: 'Nous recherchons votre séjour de rêve...',
    addedWishlist: 'Ajouté à vos favoris !',
    alreadyWishlist: 'Déjà dans vos favoris.',
    linkCopied: 'Lien copié dans le presse-papiers !',
    thankYouReview: 'Merci pour votre commentaire !',
    alreadyReviewed: 'Vous avez déjà commenté cette propriété.',
    loginToReserve: 'Veuillez vous connecter pour réserver ce séjour.',
    loginToReview: 'Veuillez vous connecter pour laisser un commentaire.',
    checkOutAfterCheckIn: 'La date de départ doit être postérieure à la date d’arrivée.',
    fillDetailsCorrectly: 'Veuillez remplir correctement tous les détails de la réservation.',
    bookingSuccessful: 'Réservation réussie ! Redirection...',
    couldNotBook: 'Impossible de créer la réservation. Veuillez vérifier la disponibilité.',
    couldNotPostReview: 'Impossible de publier le commentaire. Assurez-vous que tous les champs sont remplis.',
    couldNotSave: 'Impossible d’enregistrer. Une connexion peut être requise.',
    creditOrDebitCard: 'Carte de crédit ou de débit',
    trips: 'Voyages',
    upcomingReservations: 'Réservations à venir',
    allUpcomingReservations: 'Toute vos réservations à venir et vos souvenirs de voyage en un seul endroit.',
    stay: 'Séjour',
    noReservationsYet: 'Aucune réservation pour le moment',
    bookFirstStay: 'Réservez votre premier séjour et il apparaîtra ici.',
    startExploring: 'Commencer à explorer',
    whereYouveBeen: 'Où vous êtes allé',
    reliveMemories: 'Revivez vos souvenirs de voyage préférés',
    viewAll: 'Voir tout',
    cantFindReservation: 'Vous ne trouvez pas votre réservation ?',
    cantFindReservationDesc: 'Si vous ne voyez pas votre voyage ici, il a peut-être été réservé avec une autre adresse e-mail.',
    visitHelpCenter: 'Visiter le centre d’aide',
    historicalTripsSync: 'L’archive des voyages historiques est en cours de synchronisation.',
    saved: 'Enregistré',
    yourWishlist: 'Votre liste de favoris',
    removeFromWishlist: 'Retirer des favoris',
    noSavedStays: 'Aucun séjour enregistré pour le moment',
    clickHeartToSave: 'Cliquez sur l’icône en forme de cœur sur n’importe quelle propriété pour l’enregistrer ici pour plus tard.',
    exploreProperties: 'Explorer les propriétés',
    adminPortalTitle: 'Admin AelithraStay',
    managementPortal: 'Portail de gestion',
    propertyListings: 'Annonces immobilières',
    propertyApproval: 'Approbation des propriétés',
    disputesTitle: 'Litiges',
    reviewModeration: 'Modération des avis',
    userManagement: 'Gestion des utilisateurs',
    notificationsTitle: 'Notifications',
    analyticsTitle: 'Analyses',
    addNewListing: 'Ajouter une annonce',
    searchRecords: 'Rechercher...',
    export: 'Exporter',
    listing: 'Annonce',
    totalUsers: 'Utilisateurs totaux',
    activeListings: 'Annonces actives',
    revenueTitle: 'Revenu',
    recentReservations: 'Réservations récentes',
    quickActions: 'Actions rapides',
    userDirectory: 'Répertoire des utilisateurs',
    bookingDisputes: 'Litiges de réservation',
    propertyApprovalQueue: 'File d’attente d’approbation',
    adminNotificationCenter: 'Centre de notifications Admin',
    revenuePerformance: 'Performance des revenus',
    globalPresence: 'Présence mondiale',
    account: 'Compte',
    yourProfile: 'Votre profil',
    editProfile: 'Modifier le profil',
    securitySettings: 'Paramètres de sécurité',
    emailAddress: 'Adresse e-mail',
    phoneNumber: 'Numéro de téléphone',
    notProvided: 'Non fourni',
    about: 'À propos',
    noBioYet: 'Pas encore de bio. Parlez un peu de vous aux voyageurs et aux hôtes.',
    accountType: 'Type de compte',
    bio: 'Bio',
    profileUpdated: 'Profil mis à jour avec succès.',
    securitySettingsNotAvailable: 'Les paramètres de mot de passe et de sécurité ne sont pas encore disponibles.',
    pleaseLogin: 'Veuillez vous connecter',
    loginToViewProfile: 'Vous devez être connecté pour afficher et gérer vos paramètres de profil.',
    loginNow: 'Se connecter maintenant',
    reservationConfirmed: 'Votre réservation est confirmée !',
    confirmationEmailSent: 'Un e-mail de confirmation est en route vers votre boîte de réception.',
    confirmationCode: 'Code de confirmation',
    reservation: 'réservation',
    hostedStay: 'Séjour hébergé',
    hostIsReady: 'Votre hôte est prêt',
    checkInDetails: 'Les détails de l’arrivée seront partagés avant votre venue.',
    reservationDetails: 'Détails de la réservation',
    priceBreakdown: 'Détail du prix',
    stayTotal: 'Total du séjour',
    viewTrips: 'Voir les voyages',
    contactHost: 'Contacter l’hôte',
    printPdf: 'Imprimer en PDF',
    loadingConfirmation: 'Chargement de la confirmation...',
    gettingThere: 'Comment s’y rendre',
    arrivalInstructions: 'Consultez votre e-mail pour le plan et les instructions d’arrivée.',
    cancellationPolicy: 'Conditions d’annulation',
    reviewTripPolicies: 'Consultez les conditions de votre voyage avant de faire des modifications.',
    needHelp: 'Besoin d’aide ?',
    reachSupport: 'Contactez l’assistance depuis votre profil à tout moment.',
    hostStudio: 'Studio Hôte',
    manageEmpire: 'Gérez votre empire',
    manageEmpireDesc: 'Bon retour ! C’est ici que vous transformez votre espace en un souvenir mémorable.',
    createNewListing: 'Créer une nouvelle annonce',
    provideDetails: 'Fournissez des détails pour attirer des voyageurs du monde entier.',
    basicInformation: 'Informations de base',
    listingTitle: 'Titre de l’annonce',
    listingTitlePlaceholder: 'ex: Villa moderne minimaliste en bord de mer',
    descriptionPlaceholder: 'Dites aux voyageurs ce qui rend votre logement unique...',
    propertyType: 'Type de propriété',
    pricePerNight: 'Prix par nuit',
    addressPlaceholder: '123 Avenue des Champs',
    cityPlaceholder: 'ex: Paris',
    countryPlaceholder: 'ex: France',
    layoutCapacity: 'Agencement et capacité',
    publishListing: 'Publier l’annonce',
    publishing: 'Publication...',
    myProperties: 'Mes propriétés',
    noPropertiesListed: 'Vous n’avez pas encore d’annonces.',
    startByFillingForm: 'Commencez par remplir le formulaire à gauche.',
    listingPublished: 'Annonce publiée avec succès !',
    noPermissionHost: 'Vous n’avez pas la permission d’héberger. Veuillez vous inscrire comme hôte.',
    couldNotPublish: 'Impossible de publier l’annonce. Veuillez vérifier tous les champs.',
    listingRemoved: 'Annonce retirée.',
    hostedProperties: 'Propriétés hébergées',
    helpCenter: 'Centre d’aide',
    support: 'Assistance',
    findSolutions: 'Trouvez des solutions aux problèmes courants et contactez notre équipe.',
    tryTheseSteps: 'Essayez ces étapes :',
    checkOtherEmails: 'Vérifiez vos autres adresses e-mail :',
    checkOtherEmailsDesc: 'Vous avez peut-être utilisé une autre adresse (ex: pro vs perso) lors de la réservation.',
    searchInbox: 'Recherchez dans votre boîte de réception :',
    searchInboxDesc: 'Recherchez "AelithraStay" ou "Confirmation". N’oubliez pas de vérifier les dossiers Spams ou Promotions.',
    verifyAccount: 'Vérifiez votre compte :',
    verifyAccountDesc: 'Assurez-vous d’être connecté au bon compte sur AelithraStay.',
    waitSync: 'Attendez la synchronisation :',
    waitSyncDesc: 'Il faut parfois quelques minutes pour qu’une nouvelle réservation apparaisse.',
    faqTitle: 'Foire Aux Questions',
    faqCancelTitle: 'Comment annuler une réservation ?',
    faqCancelDesc: 'Allez dans vos Voyages, sélectionnez la réservation et cherchez le bouton "Annuler".',
    faqChargeTitle: 'Quand serai-je débité ?',
    faqChargeDesc: 'Généralement, vous êtes débité une fois que l’hôte confirme ou au moment de la réservation selon la propriété.',
    faqContactHostTitle: 'Comment contacter mon hôte ?',
    faqContactHostDesc: 'Une fois la réservation confirmée, vous trouverez le bouton "Contacter l’hôte" dans les détails du voyage.',
    stillNeedHelp: 'Encore besoin d’aide ?',
    supportDesc: 'Notre équipe d’assistance est disponible 24h/24 et 7j/7 pour vous aider.',
    contactSupport: 'Contacter l’assistance',
    backToTrips: 'Retour aux voyages',
    aboutUser: 'À propos du développeur',
    devProfile: 'Profil Développeur',
    devMission: 'Mission',
    devMissionText: 'Ingénierie d’écosystèmes numériques où la précision architecturale rencontre une sécurité sans compromis.',
    devBelief: 'AelithraStay est conçu sur la conviction absolue que les applications web modernes doivent être aussi robustes et sécurisées sous le capot qu’elles sont fluides et élégantes en surface.',
    whyAelithra: 'Pourquoi AelithraStay ?',
    devLabText: 'Ce projet est né du désir de combler le fossé entre le développement d’applications de haut niveau et la sécurité système de bas niveau. Il sert de laboratoire pour :',
    fullStackConv: 'Convergence Full-Stack',
    fullStackConvDesc: 'Intégration transparente d’une API Django REST avec un frontend Angular 21 réactif.',
    defensiveEng: 'Ingénierie Défensive',
    defensiveEngDesc: 'Mise en œuvre d’un contrôle d’accès strict, de journaux d’audit admin et de flux de suspension de compte.',
    uxFluidity: 'Fluidité UX',
    uxFluidityDesc: 'Prouver qu’un système de gestion complexe peut rester intuitif grâce à un CSS propre.',
    globalReady: 'Prêt pour l’International',
    globalReadyDesc: 'Conçu pour un public international avec un support multi-langue intégré (i18n).',
    frontendEngine: 'Moteur Frontend',
    backendCore: 'Cœur Backend',
    dataMgmt: 'Gestion des Données',
    securityAudit: 'Audit de Sécurité',
    contactDev: 'Contacter le Développeur',
    securityMindset: 'Priorité à la Sécurité',
    backToApp: 'Retour à l’Application'
  }
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  readonly current = signal<LanguageCode>('en');

  toggle(): void {
    this.current.set(this.current() === 'en' ? 'fr' : 'en');
  }

  t(key: string): string {
    return TRANSLATIONS[this.current()]?.[key] ?? TRANSLATIONS['en']?.[key] ?? key;
  }
}
